DROP DATABASE IF EXISTS wc_hub;
DROP USER IF EXISTS wc_hub;

CREATE USER wc_hub WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    CREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'wc_hub';

CREATE DATABASE wc_hub
    WITH OWNER = wc_hub
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT CONNECT ON DATABASE wc_hub TO wc_hub;
