CREATE SCHEMA wc_hub;

CREATE USER wc_hub WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'wc_hub';

GRANT CONNECT ON DATABASE wc_hub TO wc_hub;